version: '3.8'

services:
  moviemanagement:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db_postgres
      # - db_neo4j
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=movie_management

  db_postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movie_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  # Neo4j baza
  # db_neo4j:
  #   image: neo4j:5
  #   environment:
  #     NEO4J_AUTH: neo4j/password
  #   ports:
  #     - "7474:7474"
  #     - "7687:7687"
  #   volumes:
  #     - neo4j_data:/data

volumes:
  pg_data:
  # neo4j_data: